# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rollno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('interns', models.IntegerField()),
                ('workshops', models.IntegerField()),
                ('clubs', models.IntegerField()),
                ('attendance', models.FloatField()),
                ('eventsorganized', models.IntegerField()),
            ],
        ),
    ]
