# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='attendance',
            new_name='score',
        ),
    ]
